[package]
name = "parameter-store-executor"
version = "0.3.18"
edition = "2021"
authors = ["Johan Stenqvist <johan@stenqvist.net>"]

[[bin]]
name = "pse"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
clap = { version = "4.0.30", features = ["cargo"] }
tokio = { version = "1.23.0", features = ["full"] }
tokio-stream = "0.1.11"
aws-config = "0.52.0"
aws-sdk-ssm = "0.22.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-fmt", "run-cargo-clippy"]
