[package]
name = "parameter-store-executor"
version = "0.3.6"
edition = "2021"
authors = ["Johan Stenqvist <johan@stenqvist.net>"]

[[bin]]
name = "pse"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
clap = { version = "3.2.14", features = ["cargo"] }
tokio = { version = "1.20.0", features = ["full"] }
tokio-stream = "0.1.9"
aws-config = "0.46.0"
aws-sdk-ssm = "0.15.0"
