[package]
name = "parameter-store-executor"
version = "0.3.0"
edition = "2021"
authors = ["Johan Stenqvist <johan@stenqvist.net>"]

[[bin]]
name = "pse"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
clap = { version = "3.1.18", features = ["cargo"] }
tokio = { version = "1.19.2", features = ["full"] }
tokio-stream = "0.1.9"
aws-config = "0.12.0"
aws-sdk-ssm = "0.12.0"
