[package]
name = "parameter-store-executor"
version = "0.3.10"
edition = "2021"
authors = ["Johan Stenqvist <johan@stenqvist.net>"]

[[bin]]
name = "pse"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
clap = { version = "3.2.17", features = ["cargo"] }
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.9"
aws-config = "0.47.0"
aws-sdk-ssm = "0.17.0"
