[package]
name = "parameter-store-executor"
version = "0.3.27"
edition = "2021"
authors = ["Johan Stenqvist <johan@stenqvist.net>"]

[[bin]]
name = "pse"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
clap = { version = "4.3.11", features = ["cargo"] }
tokio = { version = "1.29.1", features = ["full"] }
tokio-stream = "0.1.14"
aws-config = "0.55.3"
aws-sdk-ssm = "0.28.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-fmt", "run-cargo-clippy"]
