[package]
name = "parameter-store-executor"
version = "0.2.2"
edition = "2021"
authors = ["Johan Stenqvist <johan@stenqvist.net>"]

[[bin]]
name = "pse"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.6", features = ["cargo"] }
