on:
  push:
    branches:
      - 'lab/rust'
  pull_request:

name: CI

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: cargo build --verbose

      - name: test
        run: cargo test
