on:
  push:
  pull_request:
    branches:
    - master

name: CI - test, build & release (tags)

jobs:

  ci:
    runs-on: ubuntu-16.04
    container: crystallang/crystal:0.35.1-alpine-build
    env:
      IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}

    steps:

      - uses: actions/checkout@v2

      - name: install shards
        run: shards install

      - name: run tests
        run: crystal spec

      - name: build - quick
        if: ${{ env.IS_RELEASE == 'false' }}
        run: shards build

      - name: build - release
        if: ${{ env.IS_RELEASE == 'true' }}
        run: shards build --static --release --no-debug

      - uses: actions/create-release@v1
        id: create-release
        if: ${{ env.IS_RELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - uses: actions/upload-release-asset@v1
        if: ${{ env.IS_RELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./bin/pse
          asset_name: pse
          asset_content_type: application/octet-stream
