on:
  push:
  pull_request:
    branches:
    - master

name: CI - test, build & release (tags)

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    container: crystallang/crystal:1.1.1-alpine-build
    steps:
      - uses: actions/checkout@v2

      - name: install shards
        run: shards install

      - name: run tests
        run: crystal spec

      - name: build
        run: shards build

  release:
    runs-on: ubuntu-latest
    container: crystallang/crystal:1.1.1-alpine-build
    needs: build-and-test
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:

      - uses: actions/checkout@v2

      - name: build
        run: shards build --static --release --no-debug

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: ./bin/pse
