on:
  push:
    tags-ignore:
      - '*'
  pull_request:

name: CI

jobs:

  ci:
    runs-on: ubuntu-latest
    container: crystallang/crystal:1.1.1-alpine-build
    steps:
      - uses: actions/checkout@v2

      - name: install shards
        run: shards install

      - name: run tests
        run: crystal spec

      - name: build
        run: shards build
