on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request_target:

name: CI

jobs:

  ci:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-24.04
          - target: aarch64-unknown-linux-musl
            runner: ubuntu-24.04-arm
          - target: arm-unknown-linux-musleabihf
            runner: ubuntu-24.04-arm
          - target: armv7-unknown-linux-musleabihf
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    steps:
      - name: use cached cargo binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo

      - uses: actions/checkout@v4

      - name: use cached dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-target-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: install supplemental tooling
        run: cargo install --force --locked bindgen-cli

      - name: check formatting
        run: cargo fmt --check

      - name: check linting
        run: cargo clippy --target ${{ matrix.target }} 

      - name: test
        run: cargo test --target ${{ matrix.target }}

  ci-success:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: echo Success
