on:
  push:
    tags:
      - 'v*.*.*'

name: Release

jobs:

  release:
    runs-on: ubuntu-latest
    container: crystallang/crystal:1.1.1-alpine-build
    steps:

      - uses: actions/checkout@v2

      - name: install shards
        run: shards install

      - name: run tests
        run: crystal spec

      - name: build
        run: shards build --static --release --no-debug

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./bin/pse
